name: Main Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  main-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
 
  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    uses: ./.github/workflows/deploy.yml
    if: github.event_name != 'pull_request'
    environment: dev   
  steps:
   - name: Upload to S3
     uses: actions/checkout@v2
   - name: Configure AWS credentials
     uses: aws-actions/configure-aws-credentials@v1
     with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
   - name: Update Lambda Function Configuration
    runs: |
           ls
           pwd
           aws lambda update-function-configuration \
           --function-name lambda-dev \
           --handler Geography.Serverless::Geography.Serverless.LambdaEntryPoint::FunctionHandlerAsync
      
           aws lambda update-function-code \
           --function-name lambda-dev \
           --s3-bucket hackathondotnet1 \
           --s3-key geography.zip
